window.woopaCommentLab = {
  metrics: [
    { value: "12", label: "분석 대상 영상" },
    { value: "220", label: "태깅한 고유 댓글" },
    { value: "17", label: "페르소나 후보" },
    { value: "8", label: "요청 신호 출현 영상" }
  ],
  videos: [
    { id: "FSWBbULCk-Q", shortTitle: "아반떼 500만원 인상", title: "신형 아반떼 500만원 인상", format: "가격 이슈", views: "114,715", comments: "1,280", sample: "40 스레드", signal: "가격 불안이 대안 탐색과 상호 상담으로 이어짐", implication: "분노를 반복하기보다 예산·대안·구매 시점을 정리하는 후속 포맷이 필요", url: "https://www.youtube.com/watch?v=FSWBbULCk-Q" },
    { id: "2RGBGNhqnPM", shortTitle: "지커 7X 효도 선물", title: "어머니한테 지커 7X 선물해드렸습니다", format: "오너 서사", views: "40,275", comments: "525", sample: "40 스레드", signal: "내돈내산 지지와 협찬 의심, 후속 리뷰 요청이 공존", implication: "구매 공개 뒤에는 지속 사용·검증 회차가 신뢰의 다음 단계", url: "https://www.youtube.com/watch?v=2RGBGNhqnPM" },
    { id: "RfJBHy9hSwQ", shortTitle: "채용", title: "저 혼자서는 이제 못 하겠습니다 도와주세요", format: "커뮤니티", views: "18,087", comments: "89", sample: "40 스레드", signal: "동료 지향과 새로운 콘텐츠 제안이 함께 등장", implication: "참여 요청을 일회성 채용이 아닌 콘텐츠 제안 창구로 읽을 수 있음", url: "https://www.youtube.com/watch?v=RfJBHy9hSwQ" },
    { id: "axg9ZyAWUSU", shortTitle: "그랜저 vs 렉서스", title: "한일전 신형 그랜저 vs 렉서스 ES300h", format: "비교 시승", views: "140,150", comments: "1,077", sample: "50 스레드", signal: "가격·급 논쟁과 비교 대상의 타당성 검증", implication: "비교 이유와 기준을 시작 전에 명시해야 광고·편향 의심을 줄일 수 있음", url: "https://www.youtube.com/watch?v=axg9ZyAWUSU" },
    { id: "GYJtONeV77M", shortTitle: "그랜저 풀옵 vs G80", title: "가격 차이 200만원 그랜저 풀옵 vs G80 깡통", format: "비교 시승", views: "369,373", comments: "819", sample: "50 스레드", signal: "댓글 요청 반영과 가격 겹침 비교에 대한 호응", implication: "요청 → 제작 → 회신 구조가 실제로 인지된 사례", url: "https://www.youtube.com/watch?v=GYJtONeV77M" },
    { id: "7xQxBVA2YTk", shortTitle: "마그마 GT", title: "한국 최초 미드십 V8 1,000마력 마그마 GT 공개", format: "신차 공개", views: "395,772", comments: "1,082", sample: "40 스레드", signal: "드림카 관심과 사업 연결에 대한 신뢰 리스크가 공존", implication: "조회가 큰 영상일수록 고정댓글의 사업 경험도 채널 신뢰로 읽힘", url: "https://www.youtube.com/watch?v=7xQxBVA2YTk" },
    { id: "UE7CuSyDsVY", shortTitle: "람보 타고 학교", title: "람보르기니 타고 학교 갔더니", format: "오너 서사", views: "261,796", comments: "188", sample: "40 스레드", signal: "대리만족과 포맷 확장 요청, 제작 품질 지적", implication: "감정형 콘텐츠도 후속 요청과 기본 검수의 영향을 받음", url: "https://www.youtube.com/watch?v=UE7CuSyDsVY" },
    { id: "uSyF8rBjuG4", shortTitle: "5시리즈 이벤트", title: "5시리즈 이벤트 영상이 올라오지 못했던 이유", format: "이벤트", views: "49,970", comments: "498", sample: "35 스레드", signal: "사연과 참여, 파트너 신뢰가 우호적으로 결합", implication: "이벤트는 링크만이 아니라 시청자 사연을 회수하는 포맷이 될 수 있음", url: "https://www.youtube.com/watch?v=uSyF8rBjuG4" },
    { id: "EBzBJB2YvYY", shortTitle: "스포티지 vs 라브4", title: "SUV 한일전 스포티지보다 1,034만원 비싼 라브4", format: "비교 시승", views: "136,374", comments: "721", sample: "35 스레드", signal: "실차주가 조건별 결론을 제시하고 다음 비교를 요청", implication: "댓글창의 실제 차주 경험을 판정 카드와 다음 회차 후보로 연결할 수 있음", url: "https://www.youtube.com/watch?v=EBzBJB2YvYY" },
    { id: "w_GDHNM_z0E", shortTitle: "스타리아 EV", title: "저도 샀습니다 스타리아 EV 시승기", format: "오너 시승", views: "143,766", comments: "319", sample: "35 스레드", signal: "실구매 상담, 할인 질문, 캐릭터 관심, 품질 지적이 혼재", implication: "내돈내산은 신뢰의 시작이며 조건별 정보·후속 검증이 붙어야 함", url: "https://www.youtube.com/watch?v=w_GDHNM_z0E" },
    { id: "XjfsJQ668wk", shortTitle: "중국산 테슬라 FSD", title: "애초에 불가능 중국산 테슬라 FSD, 속지마세요", format: "속보·신기술", views: "32,938", comments: "350", sample: "30 스레드", signal: "정보 번복과 업로드 순서에 대한 신뢰 감시", implication: "속보는 업데이트·정정 이력을 남기는 운영 규칙이 필요", url: "https://www.youtube.com/watch?v=XjfsJQ668wk" },
    { id: "abghK1NXYP4", shortTitle: "테슬라 6만대 FSD", title: "국내 테슬라 6만대, 드디어 FSD 열린다", format: "속보·신기술", views: "199,814", comments: "495", sample: "30 스레드", signal: "오너의 실제 조건 질문과 후속 리뷰 기대", implication: "속보의 관심을 실제 오너 검증·설정·사용기 시리즈로 이어갈 여지", url: "https://www.youtube.com/watch?v=abghK1NXYP4" }
  ],
  themes: [
    { name: "콘텐츠 요청", count: 27, ratio: 12.3, videos: 8, kind: "priority" },
    { name: "반론과 저항", count: 26, ratio: 11.8, videos: 6, kind: "constraint" },
    { name: "생활 상황과 제약", count: 21, ratio: 9.5, videos: 5, kind: "priority" },
    { name: "캐릭터 관심·변화", count: 20, ratio: 9.1, videos: 7, kind: "priority" },
    { name: "상호 상담", count: 12, ratio: 5.5, videos: 5, kind: "priority" },
    { name: "진정성·협찬 의심", count: 12, ratio: 5.5, videos: 4, kind: "priority" },
    { name: "정보 신뢰 감시", count: 11, ratio: 5.0, videos: 3, kind: "priority" },
    { name: "내돈내산 지지", count: 10, ratio: 4.5, videos: 4, kind: "priority" },
    { name: "구매 전환 직전", count: 9, ratio: 4.1, videos: 5, kind: "priority" },
    { name: "제작 품질 지적", count: 6, ratio: 2.7, videos: 4, kind: "constraint" }
  ],
  personas: [
    { id: "P1", name: "다음 편 발주자", score: 110.7, videos: 8, group: "priority", need: "내 요청이 반영됐다는 회신", current: "요청은 모이지만 선정 여부가 보이지 않음", next: "예산·후보·상황을 받는 고정 질문과 선정 회신", evidence: "C-G80-06" },
    { id: "P2", name: "배신당한 실구매자", score: 57.0, videos: 5, group: "constraint", need: "분노 이후의 현실 대안", current: "가격 상승의 불만은 크지만 채널이 가격을 바꿀 수는 없음", next: "구매 시점·대체 차종·필수 조건으로 판단을 돕기", evidence: "C-아반떼-09" },
    { id: "P3", name: "사람 보러 온 복귀자", score: 54.6, videos: 7, group: "priority", need: "우파의 변화와 근황을 만날 이유", current: "복귀 신호는 있으나 회차 구조로 설계되지 않음", next: "자동차 본편을 해치지 않는 짧은 근황·후속 약속", evidence: "C-G80-14" },
    { id: "P4", name: "댓글창 상담사", score: 49.5, videos: 5, group: "priority", need: "실제 차주 경험을 쓸 무대", current: "조건별 조언이 댓글에 묻힘", next: "오너 경험을 고정댓글·판정 카드에 회수", evidence: "C-라브4-06" },
    { id: "P5", name: "협찬 검증관", score: 49.5, videos: 4, group: "priority", need: "비교 이유와 돈의 흐름이 보이는 설명", current: "비교 대상이 어긋나면 광고·편향 의심이 커짐", next: "비교 기준·지원 관계·검증 방법을 초반에 공개", evidence: "C-한일전-08" },
    { id: "P6", name: "정보 신뢰 감시자", score: 45.0, videos: 3, group: "priority", need: "정보가 바뀌었을 때의 정정과 업데이트", current: "속보의 번복이 곧바로 신뢰 의심으로 연결", next: "고정댓글 정정과 다음 회차 업데이트 카드", evidence: "C-FSD중국-01" },
    { id: "P7", name: "내돈내산 지지자", score: 40.5, videos: 4, group: "priority", need: "구매 사실 이후의 지속 사용 기록", current: "구매 공개는 있지만 장기 검증 약속은 분산됨", next: "구매 후 30·90일 사용기와 이슈 업데이트", evidence: "C-지커효도-03" },
    { id: "P8", name: "계약 직전 대기자", score: 24.6, videos: 5, group: "priority", need: "가격·조건·연결 경로를 검증할 정보", current: "딜러·차맵 연결이 영상마다 다른 방식으로 노출", next: "정보·조건·문의 경로를 구분해 명확히 표기", evidence: "C-지커효도-18" },
    { id: "P9", name: "이탈 선언자", score: 23.6, videos: 6, group: "constraint", need: "가격 불만에 대한 대안 탐색", current: "감정 해소는 가능하지만 콘텐츠만으로 해결하기 어려움", next: "핵심 타깃보다 보조 맥락으로 활용", evidence: "C-아반떼-16" },
    { id: "P10", name: "대리만족 관람객", score: 15.0, videos: 3, group: "priority", need: "실제 탑승자 반응과 참여 장면", current: "감정형 콘텐츠는 존재하나 참여 확장이 약함", next: "탑승자·사연·후속 요청을 회차로 연결", evidence: "C-람보학교-04" },
    { id: "P11", name: "동료 지원자", score: 12.3, videos: 2, group: "constraint", need: "채널에 참여할 경로", current: "채용이라는 제한된 상황에서만 확인", next: "핵심 시청자 타깃으로 확대하지 않음", evidence: "C-채용-03" },
    { id: "P12", name: "편집 감독관", score: 10.8, videos: 4, group: "constraint", need: "기본 제작 품질", current: "중복 편집·오디오·화면 왜곡 지적이 반복", next: "업로드 전 영상·오디오·자막 검수표", evidence: "C-람보학교-03" },
    { id: "P13", name: "사연 보유자", score: 10.8, videos: 2, group: "priority", need: "차와 연결된 경험을 들려줄 자리", current: "이벤트 댓글에서만 사연이 자연스럽게 등장", next: "참여형 영상에 사연 접수와 후속 공유 장치", evidence: "C-이벤트-01" },
    { id: "P14", name: "방어에 지친 오너", score: 9.2, videos: 2, group: "priority", need: "소수 선택을 설명할 수 있는 기준", current: "브랜드 논쟁 속에서 오너 경험이 방어로 흐름", next: "조건별 선택 카드에 실제 오너 의견을 병렬 제시", evidence: "C-라브4-05" }
  ],
  quotes: [
    { id: "C-G80-06", videoId: "GYJtONeV77M", video: "그랜저 풀옵 vs G80", likes: 10, theme: "콘텐츠 요청", personas: ["P1"], text: "지난번 아우디와 비교영상에서 G80과 비교해주면 좋겠다고 했는데 구독자가 뭘 원하는지 딱 아시네요.", note: "댓글 요청 → 실제 제작 → 시청자 인지의 직접 사례." },
    { id: "C-G80-11", videoId: "GYJtONeV77M", video: "그랜저 풀옵 vs G80", likes: 0, theme: "콘텐츠 요청", personas: ["P1"], text: "아반떼 CN8 풀옵션이랑 쏘나타 깡통이랑 비교도 궁금하네요. 가격은 아반떼가 더 비싼데요.", note: "차종뿐 아니라 가격 역전이라는 비교 조건을 함께 제시." },
    { id: "C-라브4-13", videoId: "EBzBJB2YvYY", video: "스포티지 vs 라브4", likes: 0, theme: "콘텐츠 요청", personas: ["P1"], text: "스포티지 말고 5,800만원대로 구매 가능한 팰리세이드와 비교하는 건 어떨까요?", note: "다음 비교 후보와 예산 조건이 동시에 나타남." },
    { id: "C-지커효도-06", videoId: "2RGBGNhqnPM", video: "지커 7X 효도 선물", likes: 26, theme: "콘텐츠 요청", personas: ["P1", "P7"], text: "지커 출고 후 상세 리뷰 부탁드립니다.", note: "내돈내산 공개 직후 후속 검증 콘텐츠 수요." },
    { id: "C-아반떼-09", videoId: "FSWBbULCk-Q", video: "아반떼 500만원 인상", likes: 116, theme: "생활 상황과 제약", personas: ["P2", "P9"], text: "월급 모으는 속도보다 차값 오르는 속도가 더 빠르네.", note: "가격 뉴스가 실제 구매 좌절의 언어로 번짐." },
    { id: "C-아반떼-07R", videoId: "FSWBbULCk-Q", video: "아반떼 500만원 인상", likes: 3, theme: "상호 상담", personas: ["P4", "P2"], text: "가솔린 살 거면 스포티지, 하이브리드 살 거면 투싼이 정배입니다. 지금 가격에서 할인받고 사라고 하더라고요.", note: "시청자가 서로 구매 조언을 제공하는 사례." },
    { id: "C-한일전-08", videoId: "axg9ZyAWUSU", video: "그랜저 vs 렉서스", likes: 45, theme: "진정성·협찬 의심", personas: ["P5"], text: "솔직히 비교할 걸 하세요.", note: "비교 대상 설정의 타당성을 요구하는 짧고 강한 이의 제기." },
    { id: "C-한일전-07", videoId: "axg9ZyAWUSU", video: "그랜저 vs 렉서스", likes: 57, theme: "진정성·협찬 의심", personas: ["P5"], text: "이런 비교 시승의 특징은 현대차에 대해서는 절대 기본기를 언급 안 하는 거죠.", note: "비교 기준의 편향을 의심하는 신호." },
    { id: "C-지커효도-08", videoId: "2RGBGNhqnPM", video: "지커 7X 효도 선물", likes: 22, theme: "진정성·협찬 의심", personas: ["P5"], text: "뭘 받아야 이 정도까지 하시는 겁니까?", note: "내돈내산 맥락에서도 의심은 남을 수 있다는 반대 근거." },
    { id: "C-FSD중국-01", videoId: "XjfsJQ668wk", video: "중국산 테슬라 FSD", likes: 54, theme: "정보 신뢰 감시", personas: ["P6"], text: "얼마 전까지 다들 될 거라고 하더니 이젠 다들 안 된다네요.", note: "정보 변화가 신뢰 문제로 이동한 사례." },
    { id: "C-FSD중국-05", videoId: "XjfsJQ668wk", video: "중국산 테슬라 FSD", likes: 1, theme: "정보 신뢰 감시", personas: ["P6"], text: "다른 사람 영상에 상세 규제·법규 정보가 나온 뒤에 아는 척하는 사람 말은 신뢰가 좀 안 가요.", note: "시청자가 다른 채널의 업로드 순서까지 교차 확인함." },
    { id: "C-지커효도-03", videoId: "2RGBGNhqnPM", video: "지커 7X 효도 선물", likes: 63, theme: "내돈내산 지지", personas: ["P7"], text: "이분은 진짜 구매하셨네. 멋지다.", note: "직접 구매가 신뢰 자산으로 읽힌 사례." },
    { id: "C-FSD6만-07", videoId: "abghK1NXYP4", video: "테슬라 6만대 FSD", likes: 49, theme: "내돈내산 지지", personas: ["P7", "P1"], text: "우파님 취소 차량 잡으셨군요. 조만간 FSD 주행 리뷰 올라오겠군요.", note: "구매 사실을 기억하고 다음 검증 회차를 기다리는 신호." },
    { id: "C-지커효도-18", videoId: "2RGBGNhqnPM", video: "지커 7X 효도 선물", likes: 0, theme: "구매 전환 직전", personas: ["P8"], text: "영업사원 소개는 없나요? 저도 저분한테 계약하고 싶어요.", note: "영상 시청 이후 계약 경로를 묻는 공개 질문." },
    { id: "C-한일전-15", videoId: "axg9ZyAWUSU", video: "그랜저 vs 렉서스", likes: 0, theme: "구매 전환 직전", personas: ["P8"], text: "송화목 과장님 반가워요. 올해 2월 렉서스 구매자입니다.", note: "영상 속 연결 정보와 실제 구매 경험이 만나는 사례." },
    { id: "C-G80-14", videoId: "GYJtONeV77M", video: "그랜저 풀옵 vs G80", likes: 29, theme: "캐릭터 관심·변화", personas: ["P3"], text: "차 때문에 들어온 게 아니고 우파씨 모습이 바뀌어서 1년 만에 들어왔네요.", note: "인물 변화가 재방문 언어와 함께 나타난 사례." },
    { id: "C-스타리아-01", videoId: "w_GDHNM_z0E", video: "스타리아 EV", likes: 149, theme: "캐릭터 관심·변화", personas: ["P3"], text: "우파형 마운자로 리뷰해주면 안 돼요? 진짜 잘된 케이스 같은데요.", note: "자동차 영상에서도 인물 변화가 상위 관심사가 될 수 있음." },
    { id: "C-라브4-06", videoId: "EBzBJB2YvYY", video: "스포티지 vs 라브4", likes: 35, theme: "상호 상담", personas: ["P4", "P14"], text: "가격 대비와 5년 뒤 기변이면 스포티지, 차급·고속 안정성·하이브리드 내구성으로 오래 탈 거면 라브4가 맞다고 생각합니다.", note: "실제 차주가 조건별 결론을 제공한 사례." },
    { id: "C-라브4-12R", videoId: "EBzBJB2YvYY", video: "스포티지 vs 라브4", likes: 0, theme: "상호 상담", personas: ["P4"], text: "풀체인지 초기에 오류가 많을 것 같아서 현재 모델로 계약했습니다.", note: "시청자 간 의사결정 보조가 답글에서 발생." },
    { id: "C-라브4-05", videoId: "EBzBJB2YvYY", video: "스포티지 vs 라브4", likes: 36, theme: "오너 경험", personas: ["P14"], text: "라브4 차주입니다. 왜 쏘렌토 안 사고 이걸 샀는지 설명해야 하는 것 빼곤 만족합니다.", note: "소수 선택의 방어 피로가 드러나는 오너 발화." },
    { id: "C-람보학교-03", videoId: "UE7CuSyDsVY", video: "람보 타고 학교", likes: 42, theme: "제작 품질 지적", personas: ["P12"], text: "10:31 영상 중복입니다.", note: "조회 상위 감정형 영상에서도 기본 편집 오류가 눈에 띔." },
    { id: "C-스타리아-09", videoId: "w_GDHNM_z0E", video: "스타리아 EV", likes: 0, theme: "제작 품질 지적", personas: ["P12"], text: "오디오 세팅이 이상해진 건지 영상 배속이 미묘하게 빠른 건지 평소와 소리가 다르게 들립니다.", note: "기술적 신뢰는 정보 정확성뿐 아니라 제작 검수에도 연결됨." },
    { id: "C-람보학교-04", videoId: "UE7CuSyDsVY", video: "람보 타고 학교", likes: 28, theme: "대리만족", personas: ["P10"], text: "이런 영상 많이 올려주세요. 차 좋아하는 사람으로 대리만족합니다.", note: "감정형 포맷의 반복 수요." },
    { id: "C-이벤트-01", videoId: "uSyF8rBjuG4", video: "5시리즈 이벤트", likes: 0, theme: "사연", personas: ["P13"], text: "코로나 때문에 힘들었던 개인사업도 결국 다 보내줬습니다. 아직 차 없이 다니는데 5시리즈 이벤트 영상 볼 때마다 아련하네요.", note: "이벤트 영상에서 차와 인생의 사연이 자발적으로 등장." },
    { id: "C-마그마-00", videoId: "7xQxBVA2YTk", video: "마그마 GT", likes: 0, theme: "진정성·협찬 의심", personas: ["P5", "P8"], text: "우파푸른하늘 믿고 장기렌트를 알아봤는데 약속했던 내용은 지켜지지 않았고 응대도 실망스러웠습니다.", note: "채널 신뢰가 사업 경험으로 이어지는 리스크 사례. 개별 주장으로서 처리하며 일반화하지 않음." },
    { id: "C-채용-03", videoId: "RfJBHy9hSwQ", video: "채용", likes: 0, theme: "동료 지향", personas: ["P11"], text: "구독자인데 그 채널에서 함께 일한다면 부럽네요.", note: "팬덤과 참여 욕구가 채용 영상에서 보인 사례." }
  ],
  actions: [
    { number: "01", title: "요청을 받은 뒤, 선정 여부를 회신하기", evidence: "P1 · 8개 영상 · C-G80-06", observation: "비교 요청이 여러 영상에서 반복되고, 실제 반영된 사례에는 ‘구독자가 뭘 원하는지 안다’는 반응이 남음.", test: "고정댓글에 예산·후보·상황·우선순위를 받고, 다음 영상 도입 또는 고정댓글에서 선정 여부를 회신한다." },
    { number: "02", title: "비교 전에 ‘왜 이 둘인지’를 공개하기", evidence: "P5 · C-한일전-08, C-한일전-07", observation: "차급·가격·기준이 납득되지 않으면 비교 자체가 광고나 편향으로 해석됨.", test: "도입부에 가격 겹침·운행 조건·비교 규칙 중 하나를 명확히 선언하고, 비교 항목을 카드로 고정한다." },
    { number: "03", title: "실제 차주 조언을 영상의 결론으로 회수하기", evidence: "P4 · 5개 영상 · C-라브4-06", observation: "댓글창에서 이미 조건별 구매 조언과 실제 계약 경험이 오감.", test: "‘오너의 한 줄’과 조건별 판정 카드로 요약하되, 특정 댓글을 인용할 때는 동의를 받거나 익명화한다." },
    { number: "04", title: "속보에는 정정 이력을 남기기", evidence: "P6 · C-FSD중국-01", observation: "정보가 바뀌는 것보다 바뀐 사실을 어떻게 다루는지가 신뢰 판단에 연결됨.", test: "고정댓글 또는 설명란 상단에 업데이트 시각·변경 이유·다음 확인 지점을 기록한다." }
  ]
};
